In [15]:
import numpy as np
import math

k=3

X_train=np.array([[7,7],[7,4],[3,4],[1,4]])
Y_train=np.array([0,0,1,1])

X_test=np.array([[3,7],[7,3],[3,3]])
def eucl_dist(i,j):
  return np.sqrt(np.sum((i-j)**2))

def knn_algo(X_train,Y_train,X_test,k):
  y_pred=[]

  for j in range(len(X_test)):
      distances=[eucl_dist(i,j) for i in X_train]
      print(distances)
      indices=np.argsort(distances)[:k]
      print(indices)

      #classes of nearest neighbors(not unique)
      k_nearest_neighbors=Y_train[indices]
      print(k_nearest_neighbors)

      #how many nearest with unique each class
      unique_class,class_count=np.unique(k_nearest_neighbors,return_counts=True)
      #print(unique_class)
      #print(class_count)

      #taking index of most fav class and finding that class at that index in unique_class
      predicted_class=unique_class[np.argmax(class_count)]

      #appending that founf unique class in y_pred
      y_pred.append(predicted_class)
  return y_pred

y_pred=knn_algo(X_train,Y_train,X_test,k)
print(y_pred)





[9.899494936611665, 8.06225774829855, 5.0, 4.123105625617661]
[3 2 1]
[1 1 0]
[0 1]
[1 2]
[8.48528137423857, 6.708203932499369, 3.605551275463989, 3.0]
[3 2 1]
[1 1 0]
[0 1]
[1 2]
[7.0710678118654755, 5.385164807134504, 2.23606797749979, 2.23606797749979]
[2 3 1]
[1 1 0]
[0 1]
[1 2]
[1, 1, 1]
