In [150]:


import pandas as pd

columns=['label','sms_message']

# Read the tab-separated data file into a DataFrame

df = pd.read_csv('/content/drive/MyDrive/ML/SMSSpamCollection', sep='\t',names=columns)



# Display the DataFrame

print(df)


     label                                        sms_message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]


In [88]:


import matplotlib.pyplot as plt




from wordcloud import WordCloud

spam_messages = data_frame[data_frame['label'] == 'spam']




spam_text = ' '.join(spam_messages['sms_message'].tolist())





wordcloud = WordCloud(width=800, height=400, background_color='white').generate(spam_text)





plt.figure(figsize=(10, 5))




plt.imshow(wordcloud, interpolation='bilinear')




plt.axis('off')




plt.show()

KeyError: ignored

In [151]:


# Filter out the spam messages from the DataFrame

# spam_messages = data_frame[data_frame['label'] == 'spam']





# # Concatenate all the spam message contents into a single string

# spam_text = ' '.join(spam_messages['sms_message'].tolist())




# Split the spam text into individual words

words = spam_text.split()




# Count the frequency of each word

word_counts = Counter(words)




# Set the number of most repeated words you want to retrieve

num_most_common = 20




# Get the most repeated words

most_common_words = word_counts.most_common(num_most_common)




# Display the most repeated words

for word, count in most_common_words:

    print(word, count)

to 607
a 360
your 187
call 185
or 185
the 178
2 169
for 169
you 164
is 143
Call 136
on 136
have 128
and 119
from 116
ur 107
with 101
& 98
4 93
of 93


In [152]:
df

label                                        sms_message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [153]:
#data preprocessing

from sklearn.preprocessing import LabelEncoder

label_encoder=LabelEncoder()
df['label']=label_encoder.fit_transform(df['label'])
df

label                                        sms_message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      1  This is the 2nd time we have tried 2 contact u...
5568      0               Will ü b going to esplanade fr home?
5569      0  Pity, * was in mood for that. So...any other s...
5570      0  The guy did some bitching but I acted like i'd...
5571      0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [154]:
#Bag Of Words Concept/Count vectorizer
documents=['Hello ,how are you!',
           'Win money, win from home.',
           'Call me now',
           'Hello ,Call hello you tomorrow?']


In [155]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
print(cv)

CountVectorizer()


In [156]:
cv.fit(documents)

CountVectorizer()

In [157]:
cv.get_feature_names_out()

array(['are', 'call', 'from', 'hello', 'home', 'how', 'me', 'money',
       'now', 'tomorrow', 'win', 'you'], dtype=object)

In [158]:
type(cv)

sklearn.feature_extraction.text.CountVectorizer

**Build a matrix- feature values as words and row values as counts in specific documnet**

In [159]:
  cv.transform(documents).toarray()

array([[1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0],
       [0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1]])

In [160]:
matrix=pd.DataFrame(cv.transform(documents).toarray(),columns=cv.get_feature_names_out())
matrix

are  call  from  hello  home  how  me  money  now  tomorrow  win  you
0    1     0     0      1     0    1   0      0    0         0    0    1
1    0     0     1      0     1    0   0      1    0         0    2    0
2    0     1     0      0     0    0   1      0    1         0    0    0
3    0     1     0      2     0    0   0      0    0         1    0    1

In [161]:
df.head()

label                                        sms_message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

**Laoding the data**

In [162]:
Y=(df['label'])#dependent one go in Y
X=(df['sms_message'])#independent one go in X

In [163]:
type(X)

pandas.core.series.Series

In [164]:
type(Y)

pandas.core.series.Series

**Splitting**

In [165]:
#splitting
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=42)

In [166]:
type(X_train)

pandas.core.series.Series

In [167]:
X_train=X_train.values.flatten()

In [168]:
type(X_train)

numpy.ndarray

In [169]:
X_test=X_test.values.flatten()

**Text Preprocessing9**

In [170]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector=CountVectorizer()
#fir the training data & transform & this return matrix -1D array as param
train_data=count_vector.fit_transform(X_train)
test_data=count_vector.transform(X_test)

print(train_data)


  (0, 7277)	1
  (0, 1046)	1
  (0, 7003)	1
  (0, 4582)	1
  (0, 2051)	1
  (0, 7453)	1
  (0, 3230)	1
  (0, 1244)	1
  (0, 5803)	1
  (0, 6690)	2
  (0, 5446)	1
  (0, 698)	1
  (0, 5243)	1
  (0, 5586)	1
  (0, 1757)	2
  (0, 1549)	1
  (0, 193)	1
  (0, 1814)	1
  (0, 3804)	1
  (0, 6999)	1
  (0, 268)	1
  (0, 3376)	1
  (0, 4771)	1
  (1, 7453)	1
  (1, 6079)	1
  :	:
  (4174, 7328)	1
  (4174, 2425)	1
  (4174, 7312)	1
  (4175, 1549)	1
  (4175, 4008)	1
  (4175, 3881)	1
  (4175, 6128)	1
  (4176, 2894)	1
  (4176, 3251)	1
  (4176, 5432)	1
  (4176, 5171)	1
  (4176, 6133)	1
  (4176, 6132)	1
  (4177, 4674)	1
  (4177, 5832)	1
  (4177, 6706)	1
  (4177, 3699)	1
  (4178, 3239)	1
  (4178, 3728)	1
  (4178, 3600)	1
  (4178, 2220)	1
  (4178, 5732)	1
  (4178, 6474)	1
  (4178, 6094)	1
  (4178, 4525)	1


In [171]:
print(test_data)

  (0, 1149)	1
  (0, 1746)	1
  (0, 2055)	1
  (0, 2163)	1
  (0, 2999)	1
  (0, 3226)	1
  (0, 3397)	2
  (0, 3456)	2
  (0, 3600)	1
  (0, 3962)	1
  (0, 4103)	1
  (0, 4244)	1
  (0, 4505)	1
  (0, 4641)	1
  (0, 4965)	1
  (0, 6079)	1
  (0, 6615)	1
  (1, 895)	1
  (1, 926)	1
  (1, 1353)	1
  (1, 1966)	1
  (1, 2824)	1
  (1, 3300)	2
  (1, 3445)	1
  (1, 4047)	1
  :	:
  (1390, 4040)	1
  (1390, 4740)	1
  (1390, 7151)	2
  (1391, 1966)	1
  (1391, 2690)	1
  (1391, 3728)	1
  (1391, 4715)	1
  (1391, 4759)	1
  (1391, 4844)	1
  (1391, 5026)	1
  (1391, 5151)	1
  (1391, 6076)	1
  (1391, 6270)	1
  (1391, 6594)	1
  (1391, 6730)	1
  (1391, 6941)	1
  (1391, 7113)	1
  (1391, 7437)	1
  (1392, 2220)	1
  (1392, 4156)	1
  (1392, 4295)	1
  (1392, 4625)	1
  (1392, 4802)	1
  (1392, 6585)	1
  (1392, 7453)	1


In [172]:
train_data.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [173]:
test_data.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [174]:
count_vector.get_feature_names_out(test_data)

array(['00', '000', '000pes', ..., 'zouk', 'zyada', 'èn'], dtype=object)

In [175]:
count_vector.get_feature_names_out(train_data)

array(['00', '000', '000pes', ..., 'zouk', 'zyada', 'èn'], dtype=object)

**train the data**

In [176]:
type(train_data)

scipy.sparse._csr.csr_matrix

In [177]:
type(Y_train)

pandas.core.series.Series

In [178]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(train_data,Y_train)

MultinomialNB()

In [179]:
y_pred=model.predict(test_data)

In [180]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_pred,Y_test)
accuracy

0.9885139985642498

In [187]:
accuracy_score(model.predict(train_data),Y_train)


0.9932998324958124

In [189]:
score=model.score(count_vector.transform(X.values.flatten()),Y)
score

0.9921033740129217

In [182]:
X

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...                        
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: sms_message, Length: 5572, dtype: object

In [183]:
from sklearn.metrics import classification_report
print(classification_report(Y,model.predict(count_vector.transform(X.values.flatten()))))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      4825
           1       0.98      0.96      0.97       747

    accuracy                           0.99      5572
   macro avg       0.99      0.98      0.98      5572
weighted avg       0.99      0.99      0.99      5572



In [ ]:
!pip install gradio

In [191]:


import gradio as gr

import pandas as pd

# Define the prediction function

def spam_detection(email):

    transformed_email = count_vector.transform([email])

    prediction = model.predict(transformed_email)

    correct_data = label_encoder.inverse_transform(prediction)

    if correct_data[0] == 'spam':

        return "This email is classified as SPAM."

    else:

        return "This email is classified as NOT SPAM."




# Create the Gradio interface

inputs = gr.inputs.Textbox(label="Enter Email Text")

outputs = gr.outputs.Textbox(label="Prediction")




gr.Interface(spam_detection, inputs, outputs, title="Spam Email Detection").launch()




/usr/local/lib/python3.10/dist-packages/gradio/inputs.py:27: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/gradio/inputs.py:30: UserWarning: `optional` parameter is deprecated, and it has no effect
  super().__init__(
/usr/local/lib/python3.10/dist-packages/gradio/inputs.py:30: UserWarning: `numeric` parameter is deprecated, and it has no effect
  super().__init__(
/usr/local/lib/python3.10/dist-packages/gradio/outputs.py:22: UserWarning: Usage of gradio.outputs is deprecated, and will not be supported in the future, please import your components from gradio.components
  warnings.warn(


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Note: opening Chrome Inspector may crash demo inside Colab notebooks.

To create a public link, set `share=True` in `launch()`.


<IPython.core.display.Javascript object>